# Generated by Django 6.0.6 on 2026-06-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock de Producto',
                'verbose_name_plural': 'Stock de Productos',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Entrada (Abastecimiento)'), ('OUT', 'Salida (Venta/Ajuste)')], max_length=3, verbose_name='Tipo de Transacción')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Transacción de Stock',
                'verbose_name_plural': 'Transacciones de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
